apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-env
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.env_vars.aspnetcore_environment }}
  ASPNETCORE_ENVIRONMENT: "{{ .Values.env_vars.aspnetcore_environment }}"
  {{ else }}
  ASPNETCORE_ENVIRONMENT:  "{{ .Release.Namespace }}"
  {{ end }}
  LOG_JSON: "{{ .Values.env_vars.log.json }}"
  LOG_MINIMUMLEVEL: "{{ .Values.env_vars.log.minimumlevel }}"
  KAFKA_TOPIC: "{{ .Values.env_vars.kafka.topic }}"
  KAFKA_CONSUMER_GROUP: "{{ .Values.env_vars.kafka.consumer_group }}"
  KAFKA_HOST: "{{ .Values.env_vars.kafka.host }}"
