# Default values for company-api
# This file is in YAML format
# Declared variables to be passed into $/templates files

appName: company-api
namespace: phoenix-prod

image:
  repository: 988207228673.dkr.ecr.eu-central-1.amazonaws.com/phoenix-company-api
  tag: prod
  pullPolicy: Always

imagePullSecrets: []

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# replicacount has no impact if autoscaling.enabled = true
replicacount: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 85

dns:
  internal: prod.sgp.private.wiley.host
  external: prod.sgp.wiley.host

env_vars:
  aspnetcore_environment: prod
  log:
    json: true
    minimumlevel: Warning
  kafka:
    topic: wly.glb.pl.account,wly.glb.pl.organization
    host: b-1.eksprodeu.5cp134.c8.kafka.eu-central-1.amazonaws.com:9092,b-2.eksprodeu.5cp134.c8.kafka.eu-central-1.amazonaws.com:9092
  opa:
    base_url: http://opa/
  keycloak:
    base_url: https://keycloak.prod.sgp.wiley.host
    realm: phoenix
    audience: account
externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-prod-eu-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: eks/phoenix
    nameValue: API_KEY
    propertyValue: COMPANY_API_KEY
  - keyValue: eks/phoenix
    nameValue: COMPANYAPI_CONNECTION_STRING
    propertyValue: COMPANYAPI_CONNECTION_STRING
